# task to start and stop frtb-tools
---
- name: stop frtb-tools
  shell: /bns/frtb/apps/frtb-tools/bin/stop-frtb-tools.sh
  ignore_errors: yes
  register: status
  failed_when: >
    ('Terminated' not in status.stdout) and ('Nothing to stop' not in status.stdout)
when: target_action == "stop"
    
- block:
  - name: start frtb-tools
    shell: /bns/frtb/apps/frtb-tools/bin/start-frtb-tools.sh

  - name: Get process count
    shell: ps -elf | grep -i frtb-tools | grep -v grep | wc -l
    register: count
  
  - name: Fail if frtb-tools did not start   
    fail:
      msg: "frtb-tools failed to start. Process count : {{ count.stdout }}"
    when: count.stdout | int == 0
  when: target_action == "start"
