# task to start and stop fnbs-ui
---
- name: start fnbs-ui
  shell: /opt/app/fnbs/apps/fnbs-ui/bin/start.sh
  ignore_errors: yes
  register: status
  failed_when: "'Tomcat started' not in status.stdout"
when: target_action == "start"
    
- block:
  - name: stop fnbs-ui
    shell: /opt/app/fnbs/apps/fnbs-ui/bin/stop.sh
    ignore_errors: yes

  - name: Get process count
    shell: ps -elf | grep -i fnbs-ui | grep -v grep | wc -l
    register: count
    
  
  - name: Fail if fnbs-ui did not stop   
    fail:
      msg: "risk-weight-service failed to start. Process count : {{ count.stdout }}"
    when: count.stdout | int != 0
  when: target_action == "stop"
