# task to start and stop fnbs-report
---
- name: stop fnbs-report
  shell: /opt/app/fnbs/apps/fnbs-report/bin/stop.sh
  register: status
  failed_when: ('terminated' not in status.stdout) and ('Nothing to stop' not in status.stdout)
when: target_action == "stop"
    
- block:
  - name: start fnbs-report
    shell: export JAVA_HOME=/opt/app/fnbs/cfg/jdk21; /opt/app/fnbs/apps/fnbs-report/bin/start.sh

  - name: Get process count
    shell: ps -elf | grep -i fnbs-report | grep -v grep | wc -l
    register: count
  
  - name: Fail if fnbs-report did not start   
    fail:
      msg: "fnbs-report failed to start. Process count : {{ count.stdout }}"
    when: count.stdout | int == 0
  when: target_action == "start"
