- name: "{{ target_action }} fnbs-starter-bcbs"
  shell: /opt/app/fnbs/apps/fnbs-starter/bin/{{ target_action }}.sh
  register: bcbs_status
  failed_when: >
    (target_action == 'stop') and
    ('terminated' not in bcbs_status.stdout) and
    ('Nothing to stop' not in bcbs_status.stdout)

- name: "{{ target_action }} fnbs-starter-crr2"
  shell: /opt/app/fnbs/apps/fnbs-starter/bin/{{ target_action }}_crr2.sh
  register: crr2_status
  failed_when: >
    (target_action == 'stop') and
    ('terminated' not in crr2_status.stdout) and
    ('Nothing to stop' not in crr2_status.stdout)

- block:
    - name: Get process
      shell: ps -elf | grep -i fnbs-starter | grep -v grep
      register: process

    - debug:
        msg: "{{ process.stdout }}"

    - name: Fail if fnbs-starter not started completely
      fail:
        msg: "fnbs-starter-bcbs or fnbs-starter-crr2 not started"
      when: >
        ('fnbs-starter-bcbs' not in process.stdout) or
        ('fnbs-starter-crr2' not in process.stdout)
  when: target_action == "start"

