# task to start and stop fnbs-ae-etl
---
- name: stop fnbs-ae-etl
  shell: /opt/app/fnbs/apps/fnbs-ae-etl/bin/stop-ae-etl.sh
  register: status
  failed_when: >
    ('terminated' not in status.stdout) and ('Nothing to stop' not in status.stdout)
when: target_action == "stop"
    
- block:
  - name: start fnbs-ae-etl
    shell: /opt/app/fnbs/apps/fnbs-ae-etl/bin/start-ae-etl.sh

  - name: Get process count
    shell: ps -elf | grep -i fnbs-ae-etl | grep -v grep | wc -l
    register: count
  
  - name: Fail if fnbs-ae-etl did not start   
    fail:
      msg: "fnbs-ae-etl failed to start. Process count : {{ count.stdout }}"
    when: count.stdout | int == 0
  when: target_action == "start"
