---
- name: TDS - Stop / Start application
  hosts: "{{ target_server }}"
  gather_facts: false
  pre_tasks:
    - name: Load account map
      include_vars:
        file: vars/run_accounts.yml

    - name: Set run_account fact
      set_fact:
        run_account: "{{ run_accounts_map[inventory_hostname] }}"

  tasks:
    - name: Application Management Tasks
      become: true
      become_user: "{{ run_account }}"
      block:
        - name: Manage Airflow
          include_tasks: tasks/airflow.yaml
          when: target_service in ['airflow', 'ALL']

        - name: Manage NiFi
          include_tasks: tasks/nifi.yaml
          when: target_service in ['nifi', 'ALL']

        - name: Manage TDS BT
          include_tasks: tasks/tds_bt.yaml
          when: target_service in ['tds_bt', 'ALL']

        - name: Manage TDS UI
          include_tasks: tasks/tds_ui.yaml
          when: target_service in ['tds_ui', 'ALL']