---
- name: TDS - Stop / Start application
  hosts: "{{ target_server }}"
  vars_files:
    - vars/run_accounts.yaml
  become: true
  become_user: "{{ run_accounts_map[inventory_hostname] | default('tdsrun') }}"
  gather_facts: false
  tasks:
    - name: "{{ target_action }} {{ item }}"
      include_tasks: "tasks/{{ item }}.yaml"
      loop:
        - airflow
        - nifi
        - tds_bt
        - tds_ui
      when: target_service in [item, 'ALL']