# ======================================================================
# Author:               Goran Wong
# Description:          RHS Start / Stop template
# Version:              v6
# Updated:              2025-10-30
# ----------------------------------------------------------------------
# Survey Variables: 
# - target_server (Target Server)
# - target_action (start / stop application)
# ======================================================================
---
- name: RHS - Start / Stop Applications
  hosts: "{{ target_server }}"
  gather_facts: False
  become: true
  tasks:
  - name: "{{ target_action }} airflow"
    include_tasks: tasks/airflow.yaml

  - name: "{{ target_action }} guard service"
    include_tasks: tasks/guard.yaml

